previews:
  generation: automatic # Enable preview environments

services:
  - type: web
    name: frontend
    runtime: static
    staticPublishPath: ./client/dist
    buildCommand: task build-client
