services:
  - type: web
    name: frontend
    runtime: static
    staticPublishPath: ./client/dist
    buildCommand: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d && ./bin/task build-client
